/**
 * Templates written to a cache dir at runtime by `vtex run-local`.
 *
 * `RUNNER_JS` is plain JavaScript (ES modules). It is NOT TypeScript on
 * purpose — keeping it as JS sidesteps any TS-loader dependency for
 * the runner itself. The user's `entrypoint:` is still allowed to be
 * `.ts`; `tsx` handles the dynamic import.
 *
 * The string uses `String.raw` so backslashes inside regex literals
 * survive without double-escaping. The runner avoids template literal
 * interpolation (`${...}`) to keep this template parsable here.
 */

export const RUNNER_JS = String.raw`/* Generated by vtex run-local — do not edit by hand. */
import { readFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { Readable } from 'node:stream';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parse as parseYaml } from 'yaml';

const EXTENSION_DIR =
  process.env.EXTENSION_DIR ||
  dirname(fileURLToPath(import.meta.url));
const MANIFEST_PATH = join(EXTENSION_DIR, 'extension.yaml');

// Regex metacharacters that we escape before turning a route pattern
// into a RegExp. '*' is left untouched on purpose so it can be
// rewritten to '(.*)' as the trailing-wildcard form. ADR-0011.
const META_CHARS = '.+?^()|[]{}\\$';

function escapeRegex(s) {
  let out = '';
  for (const c of s) {
    if (META_CHARS.indexOf(c) !== -1) out += '\\' + c;
    else out += c;
  }
  return out;
}

function normalizeRoutes(routes) {
  return routes.map(function (r) {
    if (typeof r === 'string') return { path: r, methods: ['GET'] };
    const methods = (r.methods || ['GET']).map(function (m) {
      return m.toUpperCase();
    });
    return { path: r.path, methods: methods };
  });
}

function compileRoute(route) {
  const paramNames = [];
  let pattern = escapeRegex(route.path);
  pattern = pattern.replace(/:([A-Za-z_][A-Za-z0-9_]*)/g, function (_, name) {
    paramNames.push(name);
    return '([^/]+)';
  });
  pattern = pattern.replace(/\*/g, '(.*)');
  return {
    path: route.path,
    methods: route.methods,
    regexp: new RegExp('^' + pattern + '$'),
    paramNames: paramNames,
  };
}

function matchRoute(routes, method, pathname) {
  for (const route of routes) {
    if (route.methods.indexOf(method) === -1) continue;
    const m = route.regexp.exec(pathname);
    if (!m) continue;
    const params = {};
    route.paramNames.forEach(function (name, i) {
      params[name] = m[i + 1];
    });
    return { route: route, params: params };
  }
  return null;
}

function toFetchRequest(req) {
  const host = req.headers.host || 'localhost';
  const url = 'http://' + host + (req.url || '/');
  const method = (req.method || 'GET').toUpperCase();

  const headers = new Headers();
  for (const k of Object.keys(req.headers)) {
    const v = req.headers[k];
    if (Array.isArray(v)) {
      v.forEach(function (vv) {
        headers.append(k, vv);
      });
    } else if (v != null) {
      headers.set(k, String(v));
    }
  }

  const init = { method: method, headers: headers };
  if (method !== 'GET' && method !== 'HEAD') {
    init.body = Readable.toWeb(req);
    init.duplex = 'half';
  }
  return new Request(url, init);
}

async function writeFetchResponse(res, response) {
  res.statusCode = response.status;
  response.headers.forEach(function (v, k) {
    res.setHeader(k, v);
  });
  if (response.body) {
    const reader = response.body.getReader();
    while (true) {
      const r = await reader.read();
      if (r.done) break;
      res.write(r.value);
    }
  }
  res.end();
}

async function main() {
  const raw = await readFile(MANIFEST_PATH, 'utf8');
  const manifest = parseYaml(raw);

  const entrypointPath = resolve(EXTENSION_DIR, manifest.entrypoint);
  const mod = await import(pathToFileURL(entrypointPath).href);
  const handler = mod.default;
  if (typeof handler !== 'function') {
    throw new Error(
      'entrypoint ' + manifest.entrypoint + ' must export a default function',
    );
  }

  const declared = normalizeRoutes(manifest.routes).map(compileRoute);
  const eventsRoute =
    manifest.events && manifest.events.length
      ? compileRoute({ path: '/_events', methods: ['POST'] })
      : null;

  const port = Number(process.env.PORT || 8080);

  const server = createServer(async function (req, res) {
    try {
      const host = req.headers.host || 'localhost';
      const url = new URL(req.url || '/', 'http://' + host);
      const method = (req.method || 'GET').toUpperCase();

      let matched = matchRoute(declared, method, url.pathname);
      if (
        !matched &&
        eventsRoute &&
        url.pathname === '/_events' &&
        method === 'POST'
      ) {
        matched = { route: eventsRoute, params: {} };
      }

      if (!matched) {
        res.statusCode = 404;
        res.end('not found');
        return;
      }

      const envelope = {
        route: { path: matched.route.path, method: method },
        params: matched.params,
        request: toFetchRequest(req),
      };

      const response = await handler(envelope);
      if (!(response instanceof Response)) {
        throw new Error('handler must return a Response');
      }
      await writeFetchResponse(res, response);
    } catch (err) {
      console.error(err);
      if (!res.headersSent) {
        res.statusCode = 500;
        res.end('internal error: ' + err.message);
      }
    }
  });

  server.listen(port, function () {
    console.log(
      '[' + manifest.name + '] listening on http://localhost:' + port,
    );
    console.log('routes:');
    for (const r of declared) {
      console.log('  ' + r.methods.join(',').padEnd(10) + ' ' + r.path);
    }
    if (eventsRoute) {
      console.log(
        '  POST       /_events  (topics: ' + manifest.events.join(', ') + ')',
      );
    }
  });

  // Graceful shutdown — stop accepting new connections and let in-flight
  // requests drain. Without this, the HTTP server keeps the event loop
  // alive and tsx eventually has to force-kill (the noisy "Previous
  // process hasn't exited yet. Force killing..." message).
  function shutdown() {
    server.close(function () {
      process.exit(0);
    });
    // Hard cap — if a slow client refuses to disconnect, do not hang
    // the dev terminal forever.
    setTimeout(function () {
      process.exit(0);
    }, 1500).unref();
  }
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

main().catch(function (err) {
  console.error(err);
  process.exit(1);
});
`

/**
 * `package.json` for the runner cache dir. Pinned ranges chosen to be
 * permissive (caret) on the minor since the runner is internal tooling
 * and we want npm install to be fast (resolves to whatever was cached
 * if available).
 */
export const RUNNER_PACKAGE_JSON = JSON.stringify(
  {
    name: 'vtex-run-local-runner',
    private: true,
    type: 'module',
    description: 'Ephemeral runner spawned by `vtex run-local`. Do not edit.',
    dependencies: {
      yaml: '^2.6.0',
    },
    devDependencies: {
      tsx: '^4.19.0',
    },
  },
  null,
  2,
)

/**
 * Bumped whenever RUNNER_JS or RUNNER_PACKAGE_JSON change in a way
 * that should invalidate the cached `node_modules`. The cache dir
 * embeds this in its path so older caches are simply ignored (and the
 * dev can `rm -rf ~/.vtex/run-local-cache` to reclaim disk).
 */
export const RUNNER_CACHE_VERSION = 'v1'
