export const enum ErrorKinds {
  DEPRECATION_CHECK_ERROR = 'DeprecationCheckError',
  EDITION_REQUEST_ERROR = 'EditionRequestError',
  EVOLUTION_MANAGER_REPORT_ERROR = 'EvolutionManagerReportError',
  GENERIC_ERROR = 'GenericError',
  INVALID_OR_EXPIRED_TOKEN_ERROR = 'InvalidOrExpiredTokenError',
  OUTDATED_CHECK_ERROR = 'OutdatedCheckError',
  REQUEST_ERROR = 'RequestError',
  SETUP_TOOLING_ERROR = 'SetupToolingError',
  SETUP_TSCONFIG_ERROR = 'SetupTSConfigError',
  SETUP_TYPINGS_ERROR = 'SetupTypingsError',
  SSE_ERROR = 'SSEError',
  TELEMETRY_REPORTER_ERROR = 'TelemetryReporterError',
  TOOLBELT_CONFIG_MESSAGES_ERROR = 'ToolbeltConfigMessagesError',
}
